name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - "*"
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - "*"

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_SMOKE_0AF79F310 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "build" # Built app content directory - optional

      - name: Get url
        run: echo $DEPLOY_URL
        env:
          DEPLOY_URL: ${{ steps.builddeploy.outputs.static_web_app_url }}

      - name: Install browsers
        run: npx playwright install

      - name: Install dependencies
        run: npx playwright install-deps

      - name: Run tests (Chromium)
        run: npx playwright test e2e --browser=chromium
        env: 
          APP_URL: ${{ steps.builddeploy.outputs.static_web_app_url }}

      - name: Run tests (Firefox)
        run: npx playwright test e2e --browser=firefox
        env: 
          APP_URL: ${{ steps.builddeploy.outputs.static_web_app_url }}

      - name: Run tests (WebKit)
        run: npx playwright test e2e --browser=webkit
        env: 
          APP_URL: ${{ steps.builddeploy.outputs.static_web_app_url }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_SMOKE_0AF79F310 }}
          action: "close"
